(function(){
function inquiryBox(){if(S.counters.inquiries>=S.settings.inquiries)return '<div class="warn">Inquiry limit reached.</div>';return `<div class="actions"><button class="secondary" onclick="useInquiry()">Use Inquiry (${S.counters.inquiries}/${S.settings.inquiries})</button></div>`}
window.useInquiry=function(){if(S.counters.inquiries>=S.settings.inquiries)return;r15Checkpoint('Before inquiry');S.counters.inquiries++;alert(`ANNOUNCE ONLY\n\nMafia-side out: ${deadMafia().length}\nCitizen-side out: ${deadCit().length}\n\nDo not reveal names or roles.`);log('Inquiry',`Side counts announced: Mafia ${deadMafia().length}, Citizens ${deadCit().length}.`);renderDay()}
renderDay=function(){if(checkWin())return;if(S.step==='talk'){const remain=live().filter(p=>!S.talked.includes(p.id));return layout(`Day ${S.day} — Conversation`,`Public announcement: ${esc(S.lastPublic)}. Tick each active player after they have had a fair opportunity to speak.`,`${inquiryBox()}<div class="players">${live().map(p=>`<div class="row ${S.talked.includes(p.id)?'done':''}"><div><div class="name">${esc(p.name)}</div><div class="small">${S.talked.includes(p.id)?'Completed':'Waiting to speak'}</div></div><button ${S.talked.includes(p.id)?'disabled':''} onclick="markTalked('${p.id}')">✓ Spoke</button></div>`).join('')}</div><div class="actions"><button class="good" ${remain.length?'disabled':''} onclick="${S.day===1?'startNight()':'startNomination()'}">${S.day===1?'Move to Night 1':'Continue to Nominations'}</button></div>`)}if(S.step==='nominate-select')return nominationSelect();if(S.step==='nominate-vote')return nominationVote();if(S.step==='defence-speech')return defenceSpeech();if(S.step==='final-vote')return finalVote()}
markTalked=function(id){r15Checkpoint('Before spoke tick');if(!S.talked.includes(id))S.talked.push(id);log('Conversation',byId(id).name+' had an opportunity to speak.');renderDay()}
startNomination=function(){r15Checkpoint('Before nominations');S.step='nominate-select';S.nomination={results:[],defence:[],speechDone:[],current:''};log('Transition','Nomination stage opened.');renderDay()}
window.nominationSelect=function(){return layout(`Day ${S.day} — Nomination`,`Select one active player to nominate, or finish nominations. Each nominee must pass a conviction vote before entering defence.`,`${S.nomination.results.length?'<div class="ok">Processed: '+S.nomination.results.map(r=>esc(byId(r.id)?.name||'Unknown')+' ('+(r.passed?'Defence':'Failed')+')').join(', ')+'</div>':''}<label>Nominee</label><select id="nominee">${options(live())}</select><div class="actions"><button class="good" onclick="openConvictionVote()">Record Conviction Vote</button><button class="secondary" onclick="finishNominations()">Finish Nominations</button></div>`)}
window.openConvictionVote=function(){const id=$('nominee').value;if(!id)return alert('Select a nominee.');if(S.nomination.results.some(r=>r.id===id))return alert('This player has already been processed.');r15Checkpoint('Before conviction vote');S.nomination.current=id;S.step='nominate-vote';renderDay()}
window.nominationVote=function(){const p=byId(S.nomination.current),eligible=live().length,need=majority(eligible);return layout(`Day ${S.day} — Conviction Vote`,`Count the votes deciding whether ${esc(p.name)} enters defence.`, `<label>Votes for conviction</label><input id="convictYes" type="number" min="0" max="${eligible}" value="0"><label>Votes against</label><input id="convictNo" type="number" min="0" max="${eligible}" value="0"><div class="warn">Eligible voters: ${eligible}. Required for defence: ${need} positive votes.</div><div class="actions"><button class="good" onclick="confirmConviction(${eligible},${need})">Calculate & Continue</button></div>`)}
window.confirmConviction=function(eligible,need){const yes=Math.max(0,+$('convictYes').value||0),no=Math.max(0,+$('convictNo').value||0);if(yes+no>eligible)return alert('Positive and negative votes cannot exceed eligible voters.');r15Checkpoint('Before conviction result');const id=S.nomination.current,passed=yes>=need;S.nomination.results.push({id,yes,no,passed});if(passed&&!S.nomination.defence.includes(id))S.nomination.defence.push(id);log('Conviction',`${byId(id).name}: ${yes} for, ${no} against — ${passed?'entered defence':'did not enter defence'}.`);S.nomination.current='';S.step='nominate-select';renderDay()}
window.finishNominations=function(){r15Checkpoint('Before defence stage');if(!S.nomination.defence.length){log('Day Result','No player entered defence.');return startNight()}S.step='defence-speech';renderDay()}
window.defenceSpeech=function(){const defs=S.nomination.defence.map(byId).filter(p=>p&&p.alive),remain=defs.filter(p=>!S.nomination.speechDone.includes(p.id));return layout(`Day ${S.day} — Defence Speeches`,'Tick each defence player after their defence is complete.',`<div class="players">${defs.map(p=>`<div class="row ${S.nomination.speechDone.includes(p.id)?'done':''}"><div class="name">${esc(p.name)}</div><button ${S.nomination.speechDone.includes(p.id)?'disabled':''} onclick="markDefenceSpeech('${p.id}')">✓ Defence Complete</button></div>`).join('')}</div><div class="actions"><button class="good" ${remain.length?'disabled':''} onclick="beginFinalVote()">Start Final Vote</button></div>`)}
window.markDefenceSpeech=function(id){r15Checkpoint('Before defence speech tick');if(!S.nomination.speechDone.includes(id))S.nomination.speechDone.push(id);log('Defence',byId(id).name+' completed defence.');renderDay()}
window.beginFinalVote=function(){r15Checkpoint('Before final vote');S.step='final-vote';renderDay()}
window.finalVote=function(){const defs=S.nomination.defence.map(byId).filter(p=>p&&p.alive);if(defs.length===1){const eligible=live().length,need=majority(eligible);return layout(`Day ${S.day} — Open Final Vote`,`Record votes to remove ${esc(defs[0].name)}.`,`<label>Votes for removal</label><input id="finalYes" type="number" min="0" max="${eligible}" value="0"><div class="warn">Eligible voters: ${eligible}. Required: ${need}.</div><div class="actions"><button class="good" onclick="processSingleFinal('${defs[0].id}',${eligible},${need})">Calculate Result</button></div>`)}const voters=live().filter(p=>!defs.some(d=>d.id===p.id)),need=majority(voters.length);return layout(`Day ${S.day} — Blind Final Vote`,'Defence players cannot vote. Every eligible voter must choose exactly one defence player.',`<div class="players">${voters.map(v=>`<div class="row"><div class="name">${esc(v.name)}</div><select id="vote_${v.id}">${options(defs)}</select></div>`).join('')}</div><div class="warn">Eligible voters: ${voters.length}. Required: ${need}.</div><div class="actions"><button class="good" onclick="processBlindFinal(${need})">Calculate Result</button></div>`)}
window.processSingleFinal=function(id,eligible,need){const yes=Math.max(0,+$('finalYes').value||0);if(yes>eligible)return alert('Votes exceed eligible voters.');r15Checkpoint('Before day result');if(yes>=need)removePlayer(id,'day vote');else log('Day Result',byId(id).name+' remained in the game.');afterDayResult()}
window.processBlindFinal=function(need){const defs=S.nomination.defence.map(byId).filter(Boolean),voters=live().filter(p=>!defs.some(d=>d.id===p.id)),totals={};defs.forEach(d=>totals[d.id]=0);for(const v of voters){const choice=$('vote_'+v.id).value;if(!choice)return alert('Every eligible voter must choose one defence player.');totals[choice]++}r15Checkpoint('Before blind vote result');const winners=Object.entries(totals).filter(([,n])=>n>=need).sort((a,b)=>b[1]-a[1]);if(winners.length===1)removePlayer(winners[0][0],'blind day vote');else log('Day Result','No defence player received the required majority.');afterDayResult()}
window.afterDayResult=function(){if(checkWin())return;startNight()}
})();
