(function(){
window.REV15=true;
function rev15Defaults(){return {inquiries:3}}
function rev15Nom(){return {results:[],defence:[],speechDone:[],current:''}}
function rev15Night(){return {stage:0,mafiaTarget:'',lecterShield:'',detectiveCheck:'',doctorSave:'',vigilanteTarget:'',privateSummary:'',publicAnnouncement:'',pendingRemoved:[]}}
window.r15Checkpoint=function(label){S.history=S.history||[];const c=JSON.parse(JSON.stringify(S));c.history=[];S.history.push({label,time:new Date().toISOString(),state:c});if(S.history.length>30)S.history.shift()}
window.r15Migrate=function(){S.settings=Object.assign({start:'',count:8,mafia:2,actions:2,selfSaves:1,gfImmune:true},rev15Defaults(),S.settings||{});S.counters=Object.assign({self:0,actions:0,inquiries:0},S.counters||{});S.nomination=Object.assign(rev15Nom(),S.nomination||{});S.nightData=Object.assign(rev15Night(),S.nightData||{});S.history=S.history||[];S.step=S.step||'setup';S.seen=S.seen||[];S.talked=S.talked||[];S.logs=S.logs||[];save();const c=document.querySelector('.credit');if(c)c.textContent='by Nima · Rev 15 Logic Locked';}
window.majority=n=>Math.floor(n/2)+1;
window.options=function(arr,allowSkip=false){return (allowSkip?'<option value="">Skip / None</option>':'<option value="">Select a player</option>')+arr.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
window.healthText=function(){return S.names.length===S.settings.count&&new Set(S.names).size===S.names.length?'✓ Setup values are valid and unique.':'⚠ Setup requires correction.'}
window.renderDash=function(){const stage=S.phase==='night'?'Step '+(S.nightData.stage+1):S.phase==='reveal'?'Player '+Math.min((S.revealIndex||0)+1,S.players.length)+'/'+S.players.length:S.step;document.getElementById('dash').innerHTML=`<div><span>Phase</span><b>${esc(label())}</b><span>${esc(stage||'')}</span></div><div><span>Mafia</span><b>${aliveMafia().length}/${deadMafia().length}</b><span>active/out</span></div><div><span>Citizens</span><b>${aliveCit().length}/${deadCit().length}</b><span>active/out</span></div><div><span>Limits</span><b>${S.counters.actions}/${S.settings.actions}</b><span>Vig · Dr ${S.counters.self}/${S.settings.selfSaves} · Inq ${S.counters.inquiries}/${S.settings.inquiries}</span></div>`}
const oldLayout=layout;layout=function(t,s,b){oldLayout(t,s,b);renderDash()}
setup=function(){const i=S.setupStep,total=9;if(i===0)return layout(`Setup 1/${total} — Start Time`,'Confirm the game start time.',`<input id="v" type="time" value="${esc(S.settings.start)}"><div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.start=$('v').value||new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}))">Confirm & Next</button></div>`);if(i===1)return layout(`Setup 2/${total} — Player Count`,'Enter total players.',`<input id="v" type="number" min="5" max="40" value="${S.settings.count}"><div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.count=Math.max(5,Math.min(40,+$('v').value||8)))">Confirm & Next</button></div>`);if(i===2)return layout(`Setup 3/${total} — Mafia Count`,'Includes all Mafia-side roles.',`<input id="v" type="number" min="1" value="${S.settings.mafia}"><div class="warn">Mafia must start lower than Citizens.</div><div class="actions"><button class="good" onclick="confirmMafiaCount()">Confirm & Next</button></div>`);if(i===3)return layout(`Setup 4/${total} — Vigilante Limit`,'Set total allowed actions.',`<input id="v" type="number" min="0" value="${S.settings.actions}"><div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.actions=Math.max(0,+$('v').value||0))">Confirm & Next</button></div>`);if(i===4)return layout(`Setup 5/${total} — Doctor Self-Saves`,'Set the self-save limit.',`<input id="v" type="number" min="0" value="${S.settings.selfSaves}"><div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.selfSaves=Math.max(0,+$('v').value||0))">Confirm & Next</button></div>`);if(i===5)return layout(`Setup 6/${total} — Inquiry Limit`,'Set how many side-count inquiries may be announced.',`<input id="v" type="number" min="0" value="${S.settings.inquiries}"><div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.inquiries=Math.max(0,+$('v').value||0))">Confirm & Next</button></div>`);if(i===6)return layout(`Setup 7/${total} — Godfather Immunity`,'Choose the rule.',`<div class="actions"><button class="good" onclick="confirmSetup(()=>S.settings.gfImmune=true)">ON</button><button class="secondary" onclick="confirmSetup(()=>S.settings.gfImmune=false)">OFF</button></div>`);if(i===7)return layout(`Setup 8/${total} — Player Names`,'Enter exactly one unique name per player.',`<textarea id="v">${esc(S.names.join('\n'))}</textarea><div id="err" class="err" style="display:none"></div><div class="actions"><button class="good" onclick="confirmNames()">Confirm Names</button></div>`);return layout(`Setup 9/${total} — Shuffle & Assign`,'Review the role pool, then start private reveal.',`<div class="ok">${healthText()}</div><div class="warn">${esc(preview())}</div><div class="actions"><button class="good" onclick="shuffleRoles()">Shuffle Roles & Start Reveal</button></div>`)}
window.confirmSetup=function(fn){r15Checkpoint('Before setup step');fn();S.setupStep=Math.min(8,S.setupStep+1);log('Setup','Step '+S.setupStep+' confirmed');setup()}
window.confirmMafiaCount=function(){const max=Math.floor((S.settings.count-1)/2),v=Math.max(1,+$('v').value||1);if(v>max)return alert('Maximum Mafia count is '+max+' for '+S.settings.count+' players.');confirmSetup(()=>S.settings.mafia=v)}
window.confirmNames=function(){const n=$('v').value.split(/\n/).map(x=>x.trim()).filter(Boolean),dups=n.filter((x,i)=>n.indexOf(x)!==i);if(n.length!==S.settings.count){$('err').style.display='block';$('err').textContent='You entered '+n.length+' names. Required: '+S.settings.count;return}if(dups.length){$('err').style.display='block';$('err').textContent='Duplicate names: '+[...new Set(dups)].join(', ');return}r15Checkpoint('Before names');S.names=n;S.setupStep=8;log('Setup','Player names confirmed');setup()}
const oldShuffle=shuffleRoles;shuffleRoles=function(){r15Checkpoint('Before shuffle');oldShuffle();S.step='Private role reveal';save()}
window.undoLast=function(){if(!S.history||!S.history.length)return alert('No previous checkpoint is available.');const h=S.history.pop(),keep=S.history;S=Object.assign(S,h.state);S.history=keep;log('Correction','Restored previous checkpoint: '+h.label);render()}
renderMenu=function(){layout('Menu','Use carefully during a live game.',`<div class="actions"><button class="secondary" onclick="render()">Return to Current Step</button><button class="secondary" onclick="undoLast()" ${S.history&&S.history.length?'':'disabled'}>Undo Last Confirmed Step</button><button class="good" onclick="renderHealth()">Health Check</button><button class="danger" onclick="confirmReset()">Start New Game / Full Reset</button></div>`)}
const oldHealth=renderHealth;renderHealth=function(){r15Migrate();oldHealth()}
})();
