(function(){
const STEPS=['sleep','mafia-wake','mafia-select','lecter','mafia-sleep','special-signal','detective','doctor','vigilante','private-summary','public-confirm'];
startNight=function(){r15Checkpoint('Before night');S.phase='night';S.night=S.day;S.step='night';S.nightData={stage:0,mafiaTarget:'',lecterShield:'',detectiveCheck:'',doctorSave:'',vigilanteTarget:'',privateSummary:'',publicAnnouncement:'',pendingRemoved:[]};log('Transition','Night '+S.night+' started.');renderNight()}
renderNight=function(){if(checkWin())return;const N=S.nightData,key=STEPS[N.stage];if(key==='sleep')return promptStep(`Night ${S.night} — Everyone Sleeps`,'Say: “Everyone, close your eyes.”','Everyone is asleep');if(key==='mafia-wake')return promptStep(`Night ${S.night} — Mafia Wakes`,'Say: “Mafia team, open your eyes and identify each other.”','Mafia identification announced');if(key==='mafia-select')return layout(`Night ${S.night} — Mafia Decision`,'The active Mafia team must choose one active Citizen-side player.',`<label>Mafia selection</label><select id="pick">${options(aliveCit())}</select><div class="actions"><button class="good" onclick="recordNight('mafiaTarget','Mafia decision recorded')">Confirm Mafia Decision</button></div>`);if(key==='lecter')return roleStep('Lecter',`Night ${S.night} — Dr. Lecter`,'Say: “Dr. Lecter, open your eyes.”',aliveMafia(),'lecterShield','Confirm Shield','Dr. Lecter shield recorded');if(key==='mafia-sleep')return promptStep(`Night ${S.night} — Mafia Sleeps`,'Say: “Mafia team, close your eyes.”','Mafia sleep announced');if(key==='special-signal')return promptStep(`Night ${S.night} — Special Citizens Signal`,'Say the standard signalling script for Vigilante, Detective and Citizen Doctor. Keep the same order and timing every night.','Special-role signalling announced');if(key==='detective')return detectiveStep15();if(key==='doctor')return doctorStep15();if(key==='vigilante')return vigilanteStep15();if(key==='private-summary')return privateSummary15();if(key==='public-confirm')return publicConfirm15()}
window.promptStep=function(title,text,logText){return layout(title,text,`<div class="actions"><button class="good" onclick="advanceNight15('${logText}')">✓ Announced & Confirmed</button></div>`)}
window.advanceNight15=function(text){r15Checkpoint('Before night step');log('Night Step',text);S.nightData.stage++;renderNight()}
window.roleStep=function(role,title,text,arr,key,button,logText){const rp=S.players.find(p=>p.role===role),active=rp&&rp.alive;if(!active)return layout(title,`${text} This is a FAKE ANNOUNCEMENT because the role is no longer active. Read it normally, wait briefly, and do not reveal that the role is out.`,`<div class="warn">PRIVATE HANDLER NOTE: Fake step. No selection will be recorded.</div><div class="actions"><button class="good" onclick="advanceNight15('${role} fake announcement completed')">✓ Fake Step Completed</button></div>`);return layout(title,text,`<label>Selection</label><select id="pick">${options(arr)}</select><div class="actions"><button class="good" onclick="recordNight('${key}','${logText}')">${button}</button></div>`)}
window.recordNight=function(key,text){const v=$('pick').value;if(!v)return alert('Select a player first.');r15Checkpoint('Before night selection');S.nightData[key]=v;log('Night Action',text);S.nightData.stage++;renderNight()}
window.detectiveStep15=function(){const det=S.players.find(p=>p.role==='Detective'),active=det&&det.alive;if(!active)return roleStep('Detective',`Night ${S.night} — Detective`,'Say: “Detective, open your eyes and choose a player.”',[],'','','');const arr=live().filter(p=>p.id!==det.id);return layout(`Night ${S.night} — Detective`,'Ask the Detective to choose one active player.',`<select id="pick">${options(arr)}</select><div class="actions"><button class="good" onclick="confirmDetective15()">Show Private Result</button></div>`)}
window.confirmDetective15=function(){const id=$('pick').value,p=byId(id);if(!p)return alert('Select a player.');r15Checkpoint('Before detective result');S.nightData.detectiveCheck=id;const result=p.role==='Godfather'?'Citizen':team(p);alert('PRIVATE DETECTIVE RESULT\n\n'+p.name+': '+result);log('Night Action','Detective check completed privately.');S.nightData.stage++;renderNight()}
window.doctorStep15=function(){const doc=S.players.find(p=>p.role==='Doctor'),active=doc&&doc.alive;if(!active)return roleStep('Doctor',`Night ${S.night} — Citizen Doctor`,'Say: “Citizen Doctor, open your eyes and choose a player to save.”',[],'','','');const allowed=live().filter(p=>p.id!==doc.id||S.counters.self<S.settings.selfSaves);return layout(`Night ${S.night} — Citizen Doctor`,'Ask the Citizen Doctor to choose one active player.',`<select id="pick">${options(allowed)}</select><div class="warn">Self-saves used: ${S.counters.self}/${S.settings.selfSaves}</div><div class="actions"><button class="good" onclick="confirmDoctor15('${doc.id}')">Confirm Save</button></div>`)}
window.confirmDoctor15=function(docId){const id=$('pick').value;if(!id)return alert('Select a player.');if(id===docId&&S.counters.self>=S.settings.selfSaves)return alert('Self-save limit reached.');r15Checkpoint('Before doctor save');if(id===docId)S.counters.self++;S.nightData.doctorSave=id;log('Night Action','Citizen Doctor save recorded.');S.nightData.stage++;renderNight()}
window.vigilanteStep15=function(){const vig=S.players.find(p=>p.role==='Vigilante'),active=vig&&vig.alive;if(!active)return roleStep('Vigilante',`Night ${S.night} — Vigilante`,'Say: “Vigilante, open your eyes.”',[],'','','');if(S.counters.actions>=S.settings.actions)return layout(`Night ${S.night} — Vigilante`,'Read the normal Vigilante prompt. The action limit has been reached, so no selection is recorded.',`<div class="warn">PRIVATE HANDLER NOTE: Action limit reached.</div><div class="actions"><button class="good" onclick="advanceNight15('Vigilante prompt completed with no remaining actions')">✓ Continue</button></div>`);const arr=live().filter(p=>p.id!==vig.id);return layout(`Night ${S.night} — Vigilante`,'The Vigilante may choose one other active player or skip.',`<select id="pick">${options(arr,true)}</select><div class="warn">Actions used: ${S.counters.actions}/${S.settings.actions}</div><div class="actions"><button class="good" onclick="confirmVigilante15()">Confirm / Skip</button></div>`)}
window.confirmVigilante15=function(){const id=$('pick').value;r15Checkpoint('Before vigilante action');S.nightData.vigilanteTarget=id;if(id)S.counters.actions++;log('Night Action',id?'Vigilante action recorded.':'Vigilante skipped.');S.nightData.stage++;renderNight()}
window.calcNight15=function(){const N=S.nightData,removed=[],notes=[];if(N.mafiaTarget){if(N.mafiaTarget===N.doctorSave)notes.push('Mafia selection was saved by Citizen Doctor.');else removed.push(N.mafiaTarget)}if(N.vigilanteTarget){const p=byId(N.vigilanteTarget),blocked=N.vigilanteTarget===N.lecterShield||(p.role==='Godfather'&&S.settings.gfImmune);if(blocked)notes.push('Vigilante action was blocked.');else if(N.vigilanteTarget===N.doctorSave)notes.push('Vigilante selection was saved by Citizen Doctor.');else if(!removed.includes(N.vigilanteTarget))removed.push(N.vigilanteTarget)}return {removed,notes}}
window.privateSummary15=function(){if(!S.nightData.privateSummary){const r=calcNight15();S.nightData.privateSummary=(r.removed.length?'Players leaving overnight: '+r.removed.map(id=>byId(id).name).join(', '):'No player leaves overnight.')+(r.notes.length?'\n'+r.notes.join(' '):'');S.nightData.publicAnnouncement=r.removed.length?r.removed.map(id=>byId(id).name).join(' and ')+' left the game overnight.':'No one left the game overnight.';S.nightData.pendingRemoved=r.removed;save()}return layout(`Night ${S.night} — Private Result Summary`,'PRIVATE: review the calculated result before announcing anything publicly.',`<div class="warn">${esc(S.nightData.privateSummary).replace(/\n/g,'<br>')}</div><div class="actions"><button class="good" onclick="confirmPrivate15()">Confirm Private Result</button><button class="secondary" onclick="undoLast()">Undo Last Step</button></div>`)}
window.confirmPrivate15=function(){r15Checkpoint('Before public announcement');log('Night Result','Private result reviewed.');S.nightData.stage++;renderNight()}
window.publicConfirm15=function(){return layout(`Night ${S.night} — Public Morning Announcement`,'Read only the public announcement below. Do not reveal roles, saves, shields or failed actions.',`<div class="ok"><b>${esc(S.nightData.publicAnnouncement)}</b></div><div class="actions"><button class="good" onclick="confirmMorning15()">✓ Announcement Made — Start Day ${S.night+1}</button><button class="secondary" onclick="undoLast()">Undo Before Announcement</button></div>`)}
window.confirmMorning15=function(){r15Checkpoint('Before applying night result');for(const id of (S.nightData.pendingRemoved||[]))removePlayer(id,'night result',false);S.lastPublic=S.nightData.publicAnnouncement;log('Public Announcement',S.lastPublic);if(checkWin())return;S.phase='day';S.day=S.night+1;S.step='talk';S.talked=[];S.nomination={results:[],defence:[],speechDone:[],current:''};save();renderDay()}
})();
